### ISSUE TITLE
SteamVR doesn't launch in Cliff House

### ISSUE THREAD

**Issue by Paladinleeds** [Paladinleeds/ShieldVR-Launcher#1]
When you click the "Launch SteamVR" button from the Cliff House, it doesn't recognise SteamVR and asks you to select an application to open the link with. If you go to select one it opens the Microsoft Store and doesn't list any applications. See attached screenshot.
![image](https://user-images.githubusercontent.com/10800494/36331484-e1efa59e-1365-11e8-876b-90c383eb6ecc.png)

**Comment by Paladinleeds** [comment]
A tip if anyone wants to test this out for themselves, you can use the guide found [here](https://www.windowscentral.com/how-use-windows-mixed-reality-simulator-windows-10-creators-update). Hopefully this helps people find a solution.

**Comment by XeroraYT** [comment]
Note;

App seems to launch just fine in 2D Mode, but will not launch when in VR.

**Comment by rwalker123** [comment]
hmm, I have created this and it works for me. Maybe you could try compiling my code and see if that works for you. If it doesn't, then it probably isn't a coding issue you are having. https://github.com/rwalker123/SteamVRLauncher

P.S. This App is published as a "private" app on the windows store and it works for others I have given access to. Microsoft won't allow this type of thing to be published "public" because you aren't allowed to launch other apps that aren't in the store.

**Comment by Paladinleeds** [comment]
@rwalker123 thanks! That's exactly what I was looking for. Code is working fine on my machine. Going to study it further and see what I can. It threw open the desktop in the Cliff House. Hopefully I can resolve this. Will study the differences between your code and mine. Will leave this open for now however (once I have got said code running in my own, then we can safely close the issue).

**Comment by Paladinleeds** [comment]
Have been able to get SteamVR to launch. However it will only launch on the initial start of the app. Closing this issue as this is a separate problem.

**Comment by rwalker123** [comment]
That is true, right now, I don't think a Universal App can tell if a desktop app is running or not. That would be nice if it could. Alternatively, you can create Desktop Bridge app, which should be able to detect it.

**Comment by Paladinleeds** [comment]
I'm not sure how the desktop bridge would work (relatively new and very much inexperienced in programming). However, you're free to take a look at the code and see if you can get it working on the button press (this is pretty important for the future). Ideally, I also want a way to be able to launch it via a variable passed to it.

If you do decide to look into this and get it working, feel free to submit a PR. I also hope to take another look at it properly when I've not got my hands full with community management.

EDIT: In commit https://github.com/Paladinleeds/ShieldVR-Launcher/commit/4a09f88c803ed753eb5e31618516ad02fc9e757f I was able to get SteamVR launching off a variable. It seems the issue is launching the app off the button. That is the challenge we need to overcome.
