### ISSUE TITLE
Read from text file

### ISSUE THREAD

**Issue by Paladinleeds** [Paladinleeds/ShieldVR-Launcher#2]
Assign the variable `uriSteamVR` from a text file. This text file will be hosted in `\AppData\Local\PaladinVR` and will be written by another UWP app.

**Comment by ghost** [comment]
See if this will help. :)

https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-read-text-from-a-file

**Comment by Paladinleeds** [comment]
Have been searching around and spotted https://docs.microsoft.com/en-us/windows/uwp/app-to-app/share-data - perhaps this could do the trick? Will read more into it and see if I can apply it myself. Assigning to self.

**Comment by ghost** [comment]
Ok no worries! Good luck 👍 💯

**Comment by Paladinleeds** [comment]
Closing issue as the upcoming Redstone 5 update makes this obsolete.
